version: 0.1

phases:
  install:
    commands:
    - echo NOP
  pre_build:
    commands:
    - # echo Restoring Project packages
    - nuget restore KRF.sln
  build:
    commands:
    - # echo Build started on `date`
    - mkdir /tmp/krf
    - xbuild /p:Configuration=Release /v:m /p:restorepackages=false /flp:LogFile="/tmp/krf/msbuild.log" KRF.sln
    - echo Build completed on `date`
  post_build:
    commands:
    - mkdir ./DeployFolders
    - mkdir ./DeployFolders/bin
    - mkdir ./DeployFolders/Content
    - mkdir ./DeployFolders/Images
    - mkdir ./DeployFolders/Content
    - mkdir ./DeployFolders/MailTemplates
    - mkdir ./DeployFolders/Scripts
    - mkdir ./DeployFolders/Views
    
    - cp /tmp/krf/msbuild.log ./DeployFolders/msbuild.log
    - # echo Copying Local Data Service binaries to Deployment folder
    - cp ./KRF.Web/favicon.ico ./DeployFolders
    - cp ./KRF.Web/Global.asax ./DeployFolders
    - cp ./KRF.Web/bin/Release/*.dll ./DeployFolders/bin
    - cp ./KRF.Web/bin/Release/*.exe ./DeployFolders/bin
    - cp ./KRF.Web/Web.Release.config ./DeployFolders/web.config
    - cp -r ./KRF.Web/Content ./DeployFolders
    - cp -r ./KRF.Web/Images ./DeployFolders
    - cp -r ./KRF.Web/MailTemplates ./DeployFolders
    - cp -r ./KRF.Web/Scripts ./DeployFolders
    - cp -r ./KRF.Web/Views ./DeployFolders

artifacts:
  files:
  - ./appspec.yml
  - ./DeployFolders/**/*
  discard-paths: no
